version: '3.9'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '80:80'
    environment:
      PMA_HOST: db
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: country-restaurant
      MYSQL_ROOT_PASSWORD: password
